plugins {
    id 'com.android.application'
}
android {
    namespace 'com.system.update'
    compileSdk 33
    defaultConfig {
        applicationId "com.system.update"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'org.java-websocket:Java-WebSocket:1.5.3'
    // JSON is part of Android SDK, but if needed for standalone: implementation 'org.json:json:20230227'
}
